SELECT CITY, LENGTH(CITY) AS LEN
FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY ASC
LIMIT 1;

SELECT CITY, LENGTH(CITY) AS LEN
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY ASC
LIMIT 1;
